project:
  name: 'CityWalkerCrop'
  run_name: 'carla_data'
  result_dir: 'results20260114crop'

training:
  batch_size: 32
  max_epochs: 10
  gpus: 1
  amp: true
  normalize_step_length: true
  resume: false
  direction_loss_weight: 5.0
  feature_loss_weight: 0.1

scheduler:
  name: 'cosine'
  step_size: 10
  gamma: 0.1

optimizer:
  name: 'adamw'
  lr: 2e-4

model:
  type: 'citywalker_crop'
  do_rgb_normalize: true
  do_resize: true
  obs_encoder:
    type: 'dinov2_vitb14'
    context_size: 5
    crop: [350, 406]
    resize: [350, 406]
    freeze: true
  output_coordinate_repr: 'euclidean'

  cord_embedding:
    type: 'input_target'
    num_freqs: 6
    include_input: true

  encoder_feat_dim: 768

  decoder:
    type: 'diff_policy'
    len_traj_pred: 5
    num_heads: 8
    num_layers: 16
    ff_dim_factor: 4
    num_diffusion_iters: 100

data:
  type: citywalk_crop
  video_dir: '/mnt/ssd3/citywalker_train_carla/videos'
  pose_dir: '/mnt/ssd3/citywalker_train_carla/world-to-camera'
  num_workers: 8
  pose_fps: 2
  video_fps: 2
  target_fps: 1
  num_train: 50000
  num_val: 1000
  num_test: 0
  input_noise: 0.1 # sigma (after normalization)
  search_window: 50 # frames
  arrived_threshold: 5 # num frame
  arrived_prob: 0.3

validation:
  num_visualize: 400
testing:
  num_visualize: 400

logging:
  enable_wandb: true  # Set to false to disable Wandb logging
  pbar_rate: 100
