checkpoint: null
perturbation: null

project:
  name: 'base-model'
  run_name: 'urban_nav_feat_mix'
  result_dir: 'base0325'

training:
  batch_size: 32
  max_epochs: 20
  gpus: 1
  amp: true
  normalize_step_length: true
  resume: false
  direction_loss_weight: 5.0
  feature_loss_weight: 0.1

scheduler:
  name: 'cosine'
  step_size: 10
  gamma: 0.1

optimizer:
  name: 'adamw'
  lr: 2e-4

model:
  type: 'flow_matching_feat'
  do_rgb_normalize: true
  do_resize: true
  obs_encoder:
    type: 'dinov2_vitb14'
    context_size: 5
    crop: [350, 630]
    resize: [350, 630]
    freeze: true
  output_coordinate_repr: 'euclidean'

  cord_embedding:
    type: 'input_target'
    num_freqs: 6
    include_input: true

  encoder_feat_dim: 768

  decoder:
    type: 'flow_matching'
    len_traj_pred: 5
    num_heads: 8
    num_layers: 16
    ff_dim_factor: 4
    num_diffusion_iters: 100

data:
  type: urban_nav_feat_mixture
  num_workers: 16
  pose_fps: 2
  video_fps: 2
  target_fps: 1
  num_train: 1400
  num_val: 50
  num_test: 0
  input_noise: 0.1
  horizontal_flip_prob: 0.5
  mixture:
    - root: '/home3/rvl/dataset/carla/v0.1'
      weight: 0.3
      camera:
        width: 640
        height: 480
        fov: 110.0
        desired_width: 640
        desired_height: 360
      # num_train: 1000    # per-dataset override (falls back to top-level)
      # num_val: 25
      # pose_subdir: pose  # default
      # feature_subdir: dino  # default
      # camera:             # per-dataset camera intrinsics (optional)
      #   width: 640
      #   height: 480
      #   fov: 110.0
      #   desired_width: 640
      #   desired_height: 360
    - root: '/home3/rvl/dataset/youtube_videos'
      weight: 0.7
      camera:
        fx: 410
        fy: 410
        cx: 320
        cy: 180
        desired_width: 640
        desired_height: 360



validation:
  num_visualize: 400
testing:
  num_visualize: 400

logging:
  enable_wandb: true
  pbar_rate: 100
